### ISSUE TITLE
Crash due to IncompatibleClassChangeError: org.hamcrest.core.IsNull

### ISSUE THREAD

**Issue by riyaz** [openid/OpenYOLO-Android#157]
Got below error in prod, its not always happening, i'm unable to reproduce but its happening in some devices, its crashing when getInstance is invoked
```
    CredentialClient client = CredentialClient.getInstance(activity);
```

```
java.lang.IncompatibleClassChangeError: org.hamcrest.core.IsNull
    at dalvik.system.DexFile.defineClassNative(Native Method)
    at dalvik.system.DexFile.defineClass(DexFile.java:226)
    at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
    at dalvik.system.DexPathList.findClass(DexPathList.java:338)
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at org.hamcrest.CoreMatchers.notNullValue(CoreMatchers.java:450)
    at org.openyolo.api.b$a.a(CredentialClientOptions.java:60)
    at org.openyolo.api.b$a.<init>(CredentialClientOptions.java:52)
    at org.openyolo.api.a.a(CredentialClient.java:111)
    at com.x.y.j.a.a(YoloHelper.java:40)
```

**Comment by ypaiag** [comment]
The same crash happened for me on Google pre launch report for Samsung Galaxy J7(2016)

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
