### ISSUE TITLE
RuntimeException in sample code

### ISSUE THREAD

**Issue by packmad** [openid/OpenYOLO-Android#159]
Running org.openyolo.demoapp.passwordlogin, I get the following exception:

```
05-01 17:13:30.014 20647-20647/org.openyolo.demoapp.passwordonly E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openyolo.demoapp.passwordonly, PID: 20647
    java.lang.RuntimeException: Error receiving broadcast Intent { act=org.openyolo.credential:B35070BB6CF9ED52 cat=[com.google.bbq.QUERY] flg=0x10 pkg=org.openyolo.demoapp.passwordonly (has extras) } in com.google.bbq.BroadcastQueryClient$ResponseHandler@70f4a2c
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.putExtra(java.lang.String, byte[])' on a null object reference
        at org.openyolo.api.internal.CredentialRetrieveActivity$CredentialRetrieveQueryCallback.onResponse(CredentialRetrieveActivity.java:135)
        at com.google.bbq.BroadcastQueryClient$PendingQuery.complete(BroadcastQueryClient.java:285)
        at com.google.bbq.BroadcastQueryClient$ResponseHandler.onReceive(BroadcastQueryClient.java:361)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4) 
        at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

while debugging, it passes the guard:
`if (response.getCredentialsAvailable()) {` at [line 130](https://github.com/openid/OpenYOLO-Android/blob/master/api/java/org/openyolo/api/internal/CredentialRetrieveActivity.java) 
but I don't have any service provider installed on my phone.

So, I have tried to install the org.openyolo.demoprovider.barbican provider, but I got the same exception.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
